module.exports = {
    // CLIENT ACTIONS
    ADD_STATE: "ADD_STATE",
    SET_CURRENT_POSITION: "SET_CURRENT_POSITION",

    // APPLICATION ACTIONS
    NAVIGATE: "NAVIGATE",
    POPSTATE: "POPSTATE",

    // ARTICLE ACTIONS
    SELECT_SIZE: "SELECT_SIZE",
    SELECT_APPEARANCE: "SELECT_APPEARANCE",
    SELECT_VIEW: "SELECT_VIEW",

    // CATALOG ACTIONS
    // TODO

    // BASKET ACTIONS
    UPDATE_BASKET: "UPDATE_BASKET",
    ADD_ARTICLE: "ADD_ARTICLE",
    ADD_ARTICLE_SUCCESS: "ADD_ARTICLE_SUCCESS",

    REMOVE_ITEM: "REMOVE_ITEM",
    REMOVE_ITEM_SUCCESS: "REMOVE_ITEM_SUCCESS",

    CHANGE_QUANTITY: "CHANGE_QUANTITY",
    CHANGE_QUANTITY_SUCCESS: "CHANGE_QUANTITY_SUCCESS",
    APPLY_VOUCHER: "APPLY_VOUCHER",

    CREATE_KEY: "CREATE_KEY",
    CREATE_KEY_SUCCESS: "CREATE_KEY_SUCCESS",
    UPDATE_KEY: "UPDATE_KEY",
    UPDATE_KEY_SUCCESS: "UPDATE_KEY_SUCCESS",
    SELECT_KEY: "SELECT_KEY",


    CREATE_TRANSLATION: "CREATE_TRANSLATION",
    CREATE_TRANSLATION_SUCCESS: "CREATE_TRANSLATION_SUCCESS",

    UPDATE_TRANSLATION: "UPDATE_TRANSLATION",
    UPDATE_TRANSLATION_SUCCESS: "UPDATE_TRANSLATION_SUCCESS"

}